name: WarpDrive
main: no.runsafe.warpdrive.Plugin
version: 1.1
author: Kruithne, mortenn
description: Public and private warps for minecraft
commands:
  sethome:
    permission: runsafe.home.set
    description: Set private warp location
  delhome:
    permission: runsafe.home.delete
    description: Remove a private warp location
  home:
    permission: runsafe.home.use
    description: Teleport to a private warp location
  setwarp:
    permission: runsafe.warp.set
    description: Set public warp location
  delwarp:
    permission: runsafe.warp.delete
    description: Remove a private warp location
  warp:
    permission: runsafe.warp.use
    description: Teleport to a private warp location
  top:
    permission: runsafe.teleport.top
    description: Teleports the player to the top block of his or her x/z coordinate.
  teleportpos:
    permission: runsafe.teleport.coordinate
    description: Teleports to a given coordinate
    aliases: [tppos]
  teleport:
    description: Teleports you to another player
    aliases: [tp]