name: WarpDrive
main: no.runsafe.warpdrive.Plugin
version: 1.1.@BUILD@
authors: [Kruithne, mortenn]
description: Public and private warps for minecraft
commands:
  sethome:
    description: Set private warp location
  delhome:
    description: Remove a private warp location
  home:
    description: Teleport to a private warp location
  setwarp:
    description: Set public warp location
  delwarp:
    description: Remove a private warp location
  warp:
    description: Teleport to a private warp location
  top:
    description: Teleports the player to the top block of his or her x/z coordinate.
  teleportpos:
    description: Teleports to a given coordinate
    aliases: [tppos]
  teleport:
    description: Teleports you to another player
    aliases: [tp]
  wipehomes:
    description: Deletes all homes in a world
  teleporttoentityid:
    description: Teleports you to the location of an entity
    aliases: [etp]